# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/cnt.xdc

# Block Designs: bd/design_ddr/design_ddr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr || ORIG_REF_NAME==design_ddr} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_mig_7series_0_0/design_ddr_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_mig_7series_0_0 || ORIG_REF_NAME==design_ddr_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_util_vector_logic_0_0/design_ddr_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_util_vector_logic_0_0 || ORIG_REF_NAME==design_ddr_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_system_ila_0_0/design_ddr_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_system_ila_0_0 || ORIG_REF_NAME==design_ddr_system_ila_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_xlconstant_0_0/design_ddr_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_xlconstant_0_0 || ORIG_REF_NAME==design_ddr_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_writer_wrapper_0_0/design_ddr_axi_writer_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_writer_wrapper_0_0 || ORIG_REF_NAME==design_ddr_axi_writer_wrapper_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_proc_sys_reset_0_1/design_ddr_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_proc_sys_reset_0_1 || ORIG_REF_NAME==design_ddr_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_vio_0_0/design_ddr_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_vio_0_0 || ORIG_REF_NAME==design_ddr_vio_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_xlconstant_1_0/design_ddr_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_xlconstant_1_0 || ORIG_REF_NAME==design_ddr_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_xbar_0/design_ddr_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==design_ddr_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_interconnect_0_0/design_ddr_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_interconnect_0_0 || ORIG_REF_NAME==design_ddr_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_uartlite_0_0/design_ddr_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_uartlite_0_0 || ORIG_REF_NAME==design_ddr_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_auto_pc_2/design_ddr_axi_interconnect_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_interconnect_0_imp_auto_pc_2 || ORIG_REF_NAME==design_ddr_axi_interconnect_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_auto_pc_0/design_ddr_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==design_ddr_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_auto_pc_1/design_ddr_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ddr_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==design_ddr_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# XDC: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/design_ddr_ooc.xdc
