# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/bd/microblaze_core_inst_0/ip/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0.xci
# IP: The module: 'microblaze_core_inst_0_lmb_bram_if_cntlr_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/bd/microblaze_core_inst_0/ip/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_core_inst_0_lmb_bram_if_cntlr_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/bd/microblaze_core_inst_0/ip/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0.xci
# IP: The module: 'microblaze_core_inst_0_lmb_bram_if_cntlr_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/bd/microblaze_core_inst_0/ip/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0/microblaze_core_inst_0_lmb_bram_if_cntlr_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_core_inst_0_lmb_bram_if_cntlr_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
