# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Vivado/Projects/project_ddr/project_ddr.srcs/sources_1/bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_xbar_0/design_ddr_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'design_ddr_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_xbar_0/design_ddr_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ddr_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Vivado/Projects/project_ddr/project_ddr.srcs/sources_1/bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_xbar_0/design_ddr_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'design_ddr_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Vivado/Projects/project_ddr/project_ddr.gen/sources_1/bd/design_ddr/ip/design_ddr_axi_interconnect_0_imp_xbar_0/design_ddr_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ddr_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
